package com.buccbracu.bucc

val skills = listOf(
    "Android Development",
    "iOS Development",
    "Web Development",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "Game Development",
    "UI/UX Design",
    "Graphic Design",
    "Product Management",
    "Project Management",
    "Quality Assurance",
    "DevOps",
    "Data Science",
    "Machine Learning",
    "Artificial Intelligence",
    "Cybersecurity",
    "Blockchain",
    "IoT",
    "AR/VR",
    "Cloud Computing",
    "Robotics",
    "JavaScript",
    "TypeScript",
    "React",
    "Angular",
    "Vue",
    "Node.js",
    "Express",
    "NestJS",
    "Python",
    "Django",
    "Flask",
    "Ruby",
    "Java",
    "Spring",
    "Kotlin",
    "Swift",
    "Flutter",
    "Dart",
    "C#",
    "Unity",
    "C++",
    "PHP",
    "Laravel",
    "Ruby on Rails",
    "HTML",
    "CSS",
    "Sass",
    "Less",
    "Bootstrap",
    "Tailwind CSS",
    "Material-UI",
    "Ant Design",
    "GraphQL",
    "Apollo",
    "REST API",
    "Firebase",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Docker",
    "Kubernetes",
    "Git",
    "AWS",
    "Azure",
    "Google Cloud",
    "Heroku",
    "Netlify",
    "Vercel",
    "DigitalOcean",
    "Socket.IO",
    "WebSockets",
    "WebRTC"
)

val allDepartments = listOf(
    "Governing Body",
    "Communication and Marketing",
    "Creative",
    "Event Management",
    "Finance",
    "Human Resources",
    "Press Release and Publications",
    "Research and Development"
)
val allDesignations = listOf(
    "President",
    "Vice President",
    "General Secretary",
    "Treasurer",
    "Director",
    "Assistant Director",
    "Senior Executive",
    "Executive",
    "General Member",
)
